apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: emilevauge/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  labels:
    app: whoami
spec:
  ports:
  - port: 80
  selector:
    app: whoami
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-rc
  labels:
    k8s-app: nginx-ingress
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress
    spec:
      containers:
      - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.18.0
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  labels:
    app: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30001
  selector:
    app: nginx-ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: my.whoami.example
    http:
      paths:
      - backend:
          serviceName: whoami-svc
          servicePort: 80
        path: /
